apiVersion: v1 
kind: Service 
metadata:
  name: backend-service 
  namespace: sp
spec: 
  selector:
    apps: shops 
  ports:
  - targetPort: 3306 
    port: 3306
  type: ClusterIP
  clusterIP: None 